options:
  email:
    type: string
    description: Account email address, this email will receive notifications from Let's Encrypt
  server:
    type: string
    description: Certificate authority server
    default: "https://acme-v02.api.letsencrypt.org/directory"
  httpreq_endpoint:
    type: string
    description: URL of the custom API that can be used to fulfill the DNS-01 challenge
  httpreq_http_timeout:
    type: int
    description: API request timeout (seconds)
    default: 30
  httpreq_mode:
    type: string
    description: "'RAW' or None"
  httpreq_password:
    type: string
    description: Basic authentication password
  httpreq_polling_interval:
    type: int
    description: Time between DNS propagation check (seconds)
    default: 2
  httpreq_propagation_timeout:
    type: int
    description: Maximum waiting time for DNS propagation (seconds)
    default: 60
  httpreq_username:
    type: string
    description: Basic authentication username
